adbcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('basic_app/', include('basic_app.urls'))
]

basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'
urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'), 
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('<str:pk>', views.SchoolDetailView.as_view(), name='detail'), 
    path('update/<str:pk>', views.SchoolUpdateView.as_view(), name='update'), 
    path('delete/<str:pk>', views.SchoolDeleteView.as_view(), name="delete")
]

basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk':self.pk})
    


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView,  ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from basic_app import models

class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    template_name = 'basic_app/school.html'



class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields=('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")
    

basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{%url 'basic_app:list'%}">Schools</a></li>
            <li><a class="navbar-link" href="{%url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-brand" href="{%url 'basic_app:create'%}">Create </a></li>
        </ul>
    </nav>
    
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

basic_app/templates/basic_app/school.html
{% extends "basic_app/basic_app_base.html" %}
{% block content %}
<h1>Welcome to a list of all the Schools</h1>
<ol>
    {% for school in schools %}
        <h2><li><a href="{{school.id}}">{{school.name}}</a></li><h2>
    {% endfor %}
</ol>
{% endblock %}

basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}
{% block content %}
<h1> Are you sure you want to Delete {{school.name}}?</h1>
<form method='POST'>
    {%csrf_token%}
    <input class="btn btn-danger" type="submit" value="delete">
    <a class="btn btn-success" href="{%url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>

{% endblock %}

basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block content %}
    <div class="jumbotron">
        <h1>
            Welcome to the school detail page
        </h1>
        <h2>School details: </h2>
        <p>Name: {{school_detail.name}}</p>
        <p>Principal: {{school_detail.principal}}</p>
        <p>Location: {{school_detail.location}}</p>
        <h3>Students: </h3>
        {% for student in school_detail.students.all %}
        <p>{{student.name}} who is {{student.age}} years old.</p>
        {% endfor %}
    </div>
    <div class="container">
        <p><a class="btn btn-warning" href="{%url 'basic_app:update' pk=school_detail.pk%}">Update</a></p>
        <p><a class="btn btn-danger" href="{%url 'basic_app:delete' pk=school_detail.pk%}">Delete</a></p>
    </div>
{% endblock %}

basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}
{% block content %}
<h1>
    {% if not form.instance.pk %}
        Create school
    {% else %}
    update school
    {% endif %}
</h1>
<form method="POST">
    {% csrf_token%}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary" value="submit">
</form>
{% endblock %}

basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block content %}
<h1>Welcome to a list of all the Schools</h1>
<ol>
    {% for school in schools %}
        <h2><li>{{school.name}}</li><h2>
    {% endfor %}
</ol>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="Jumbotron">
        <h1>Home Page!</h1>
    </div>
{% endblock %}